apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: nginx-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s