services:
  socat:
    container_name: socat
    image: alpine/socat
    restart: unless-stopped
    networks:
      - jenkins-network
    expose:
      - "2376"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: tcp-listen:2376,fork,reuseaddr unix-connect:/var/run/docker.sock
  jenkins:
    container_name: Jenkins
    image: jenkins/jenkins:lts-jdk17
    restart: unless-stopped
    networks:
      - jenkins-network
    ports:
      - 80:8080
      - 50000:50000
    volumes:
      - data:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://socat:2376

networks:
  jenkins-network: {}

volumes:
  data:
    name: jenkins-data