apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
    </source>

    <match **>
      @type elasticsearch
      host elasticsearch-master.logging.svc.cluster.local  # Adjust according to your service name
      port 9200
      logstash_format true
      index_name fluentd
      type_name _doc
      include_tag_key true
      tag_key @log_name
    </match>
