apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/nginx/access.log  # Path to NGINX access log
      pos_file /var/log/td-agent/nginx-access.pos  # Position file to track log reading progress
      tag nginx.access
      format nginx  # Parse logs in NGINX format
    </source>

    <source>
      @type tail
      path /var/log/nginx/error.log  # Path to NGINX error log
      pos_file /var/log/td-agent/nginx-error.pos
      tag nginx.error
      format nginx
    </source>

    <match nginx.**>
      @type prometheus  # Output plugin to send data to Prometheus
      logstash_format true
      index_name nginx-logs
    </match>
